version: '3.3'
services:
  database:
    image: mysql:8.0
    container_name: coffee-db
    command: --innodb-use-native-aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=${DB_NAME:-homestead}
      - MYSQL_USER=${DB_USER:-homestead}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
      - TZ=${TZ:-Asia/Ho_Chi_Minh}
    volumes:
      # - ./docker/db-data:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${DB_PORT:-3010}:3306
    stdin_open: true
    tty: true
    restart: always
  app:
    container_name: coffee-app
    build:
      context: ./docker/php/
      args:
        - TZ=${TZ:-Asia/Ho_Chi_Minh}
    ports:
      - ${APP_PORT:-9999}:8000
    volumes:
      - ${SOURCE:-./src}:/work/app:delegated
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/ash:/etc/profile.d
      - ./docker/php/psysh:/root/.config/psysh
 
    working_dir: /work/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=coffee-db
      - DB_DATABASE=${DB_NAME:-coffee-db}
      - DB_USERNAME=${DB_USER:-homestead}
      - DB_PASSWORD=${DB_PASS:-secret}
      - TZ=${TZ:-Asia/Ho_Chi_Minh}
    restart: always  

  web:
    image: nginx:1.19.10
    depends_on:
      - app
    container_name: coffee-web
    ports:
      - ${WEB_PORT:-8888}:8081
    volumes:
      - ${SOURCE:-./src}:/work/app:delegated
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template  
    environment:
      - TZ=${TZ:-Asia/Ho_Chi_Minh}
      - COMPOSE_PROJECT_NAME=app
    command: /bin/sh -c "envsubst '$$COMPOSE_PROJECT_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
  
  



