<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductsSeeder extends Seeder
{
    protected $products = [
        ["title" => "Bạc Sỉu Đá", "category_id" => 1, "link_image" => "/image/products/1.png", "description" => "Nếu không biết uống gì, hãy thử 'Ly sữa trắng kèm một chút cà phê' này ", "price" => "25000", "favorite" => 1],
        ["title" => "Americano Nóng", "category_id" => 1, "link_image" => "/image/products/2.png", "description" => "Americano được pha chế bằng cách pha thêm nước với tỷ lệ nhất định vào tách cà phê Espresso, từ đó mang lại hương vị nhẹ nhàng và giữ trọn được mùi hương cà phê đặc trưng.", "price" => "40000"],
        ["title" => "Cappuccino Nóng", "category_id" => 1, "link_image" => "/image/products/3.png", "description" => "Cappuchino là thức uống hòa quyện giữa hương thơm của sữa, vị béo của bọt kem cùng vị đậm đà từ cà phê Espresso. Tất cả tạo nên một hương vị đặc biệt, nhẹ nhàng, trầm lắng và tinh tế.", "price" => "45000", "favorite" => 1],
        ["title" => "Espresso Nóng", "category_id" => 1, "link_image" => "/image/products/4.png", "description" => "Một tách Espresso nguyên bản được bắt đầu bởi những hạt Arabica chất lượng, phối trộn với tỉ lệ cân đối hạt Robusta, cho ra vị ngọt caramel, vị chua dịu và sánh đặc.", "price" => "40000"],
        ["title" => "Mocha Đá", "category_id" => 1, "link_image" => "/image/products/5.png", "description" => "Loại cà phê được tạo nên từ sự kết hợp hoàn hảo của vị đắng đậm đà của Espresso và sốt sô-cô-la ngọt ngào mang tới hương vị đầy lôi cuốn, đánh thức mọi giác quan nên đây chính là thức uống ưa thích của phụ nữ và giới trẻ.", "price" => "50000"],
        ["title" => "Caramel Macchiato Đá", "category_id" => 1, "link_image" => "/image/products/6.png", "description" => "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt Caramel được gói gọn trong một tách cà phê.", "price" => "50000"],
        ["title" => "Coffee Đá Xay", "category_id" => 1, "link_image" => "/image/products/7.png", "description" => "Một phiên bản 'upgrade' từ ly cà phê sữa quen thuộc, nhưng lại tỉnh táo và tươi mát hơn bởi lớp đá xay đi kèm. Nhấp 1 ngụm cà phê đá xay là thấy đã, ngụm thứ hai thêm tỉnh táo và cứ thế lôi cuốn bạn đến ngụm cuối cùng.", "price" => "35000"],
        ["title" => "Coffee Đen Đá", "category_id" => 1, "link_image" => "/image/products/8.png", "description" => "Không ngọt ngào như Bạc sỉu hay Cà phê sữa, Cà phê đen mang trong mình phong vị trầm lắng, thi vị hơn. Người ta thường phải ngồi rất lâu mới cảm nhận được hết hương thơm ngào ngạt, phảng phất mùi cacao và cái đắng mượt mà trôi tuột xuống vòm họng.", "price" => "25000", "favorite" => 1],
        ["title" => "Cold Brew Phúc Bồn Tử", "category_id" => 1, "link_image" => "/image/products/9.png", "description" => "Vị chua ngọt của trái phúc bồn tử, làm dậy lên hương vị trái cây tự nhiên vốn sẵn có trong hạt cà phê, hòa quyện thêm vị đăng đắng, ngọt dịu nhẹ nhàng của Cold Brew để mang đến một cách thưởng thức cà phê hoàn toàn mới, vừa thơm lừng hương cà phê quen thuộc, vừa nhẹ nhàng và thanh mát bởi hương trái cây đầy thú vị.", "price" => "45000", "favorite" => 1],
        ["title" => "Cold Brew Truyền Thống", "category_id" => 1, "link_image" => "/image/products/10.png", "description" => "Cold Brew được ủ và phục vụ mỗi ngày từ 100% hạt Arabica Cầu Đất với hương gỗ thông, hạt dẻ, nốt sô-cô-la đặc trưng, thoang thoảng hương khói nhẹ giúp Cold Brew giữ nguyên vị tươi mới.", "price" => "40000"],
        ["title" => "Cold Brew Sữa Tươi", "category_id" => 1, "link_image" => "/image/products/11.png", "description" => "Thanh mát và cân bằng với hương vị cà phê nguyên bản 100% Arabica Cầu Đất cùng sữa tươi thơm béo cho từng ngụm tròn vị, hấp dẫn.", "price" => "45000"],
        ["title" => "Latte Đá", "category_id" => 1, "link_image" => "/image/products/12.png", "description" => "Latte, cà phê Espresso và sữa nóng được trộn lẫn vào nhau, bên trên vẫn là lớp bọt sữa nhưng mỏng và nhẹ hơn Cappucinno.", "price" => "50000"],
        ["title" => "Nitro Vanilla Cream", "category_id" => 1, "link_image" => "/image/products/13.png", "description" => "Cảm nhận sự quyến rũ của cà phê và kem va ni ngay lập tức với nitro với cổ họng êm ái", "price" => "70000"],
        ["title" => "Nitro Cold Brew", "category_id" => 1, "link_image" => "/image/products/14.png", "description" => "Cà phê nitro xếp tầng đích thực và crema lạnh mềm! Bạn có thể trải nghiệm vị ngọt tự nhiên của cà phê với cảm giác ngon miệng và cân bằng hoàn hảo.", "price" => "70000"],
        ["title" => "Dolce Cold Brew", "category_id" => 1, "link_image" => "/image/products/15.png", "description" => "Gặp gỡ Dolce Cold Brew! Sự kết hợp tuyệt vời nhất của đồ uống Starbucks", "price" => "65000"],
        ["title" => "Vanilla Cream Cold Brew", "category_id" => 1, "link_image" => "/image/products/16.png", "description" => "Với kem vani được thêm vào bia lạnh, bạn có thể thưởng thức một cốc bia lạnh ngọt ngào và sảng khoái.", "price" => "65000"],
        ["title" => "Velvet Dark Mocha Nitro", "category_id" => 1, "link_image" => "/image/products/17.png", "description" => "Với phần nhân sô cô la đen đậm đà. cà phê nitro dự trữ với độ mềm mượt như nhung với hương vị hạt phỉ và lớp bọt kem caramel ngọt ngào", "price" => "65000", "favorite" => 1],
        ["title" => "Jeju Forest Cold Brew", "category_id" => 1, "link_image" => "/image/products/18.png", "description" => "Gợi nhớ đến Bijarim Rừng Thiên niên kỷ ở Jeju. Được làm bằng matcha hữu cơ ở Jeju như một thức uống. Đồ uống sử dụng bột và ủ lạnh.", "price" => "65000"],
        ["title" => "Cold Brew", "category_id" => 1, "link_image" => "/image/products/19.png", "description" => "Bia lạnh được tạo ra từ sự chân thành của các nhân viên pha chế Starbucks! Hạt cà phê cold brew được ủ với nước lạnh trong 14 giờ, và chỉ cung cấp một lượng hạn chế. Tận hưởng trải nghiệm cà phê mới với hương vị đậm đà. ", "price" => "65000", "favorite" => 1],
        ["title" => "Cold Brew Mạch Nha", "category_id" => 1, "link_image" => "/image/products/20.png", "description" => "Bia lạnh dự trữ, kem vani và sữa lắc hỗn hợp mạch nha", "price" => "55000"],
        ["title" => "Cold Brew Oat Latte", "category_id" => 1, "link_image" => "/image/products/21.png", "description" => "Một ly latte thơm ngon kết hợp giữa với hương vị của bia lạnh và sữa yến mạch sạch. Một thức uống pha lạnh mà tất cả khách hàng có thể thưởng thức tùy tiện khi dùng sữa thực vật", "price" => "65000"],
        ["title" => "Cold Brew Float", "category_id" => 1, "link_image" => "/image/products/22.png", "description" => "Một muỗng kem vani tan chảy bên trên bánh Reserve Cold Brew", "price" => "65000"],
        ["title" => "French Apple Tarte Nitro", "category_id" => 1, "link_image" => "/image/products/23.png", "description" => "Một thức uống nitro dự trữ kết hợp hài hoà giữa vị ngọt của táo với vị caramel và lớp crema lạnh mềm", "price" => "65000"],
        ["title" => "Hồng Trà Latte Macchiato", "category_id" => 2, "link_image" => "/image/products/tea1.png", "description" => "Mỗi ngày với Hibika sẽ là điều tươi mới hơn với sữa hạt mắc ca thơm ngon, bổ dưỡng quyện cùng nền trà oolong cho vị cân bằng, ngọt dịu đi kèm cùng Trân châu trắng giòn dai mang lại cảm giác “đã” trong từng ngụm trà sữa.", "price" => "45000", "favorite" => 1],
        ["title" => "Hồng Trà Sữa Nóng", "category_id" => 2, "link_image" => "/image/products/tea2.png", "description" => "Thêm chút ngọt ngào cho ngày mới với hồng trà nguyên lá, sữa thơm ngậy được cân chỉnh với tỉ lệ hoàn hảo, cùng trân châu trắng dai giòn có sẵn để bạn tận hưởng từng ngụm trà sữa ngọt ngào thơm ngậy thiệt đã.", "price" => "40000"],
        ["title" => "Hồng Trà Sữa Trân Châu", "category_id" => 2, "link_image" => "/image/products/tea3.png", "description" => "Trà sữa không đã ngon, nay còn có thêm trân châu thì phải nói là ... 10 điểm", "price" => "44000"],
        ["title" => "Trà Sữa Mắc Ca Trân Châu Trắng", "category_id" => 2, "link_image" => "/image/products/tea4.png", "description" => "Trà sữa Mắc ca Trân châu trắng là sự kết hợp giữa nền trà Oolong hảo hạng thơm lừng, cùng sữa hạt Mắc Ca bổ dưỡng ngọt dịu ít béo, đặc biệt là topping trân châu trắng dai giòn hấp dẫn.", "price" => "50000"],
        ["title" => "Trà Hạt Sen Đá", "category_id" => 2, "link_image" => "/image/products/tea5.png", "description" => "Nền trà ô long hảo hạng kết hợp cùng hạt sen tươi, bùi bùi và lớp foam cheese béo ngậy. Trà hạt sen là thức uống thanh mát, nhẹ nhàng phù hợp cho cả buổi sáng và chiều tối. Uống đá sẽ cho một cảm giác mát mẻ, sảng khoái trong nhũng ngày hè.", "price" => "35000"],
        ["title" => "Trà Hạt Sen Nóng", "category_id" => 2, "link_image" => "/image/products/tea6.png", "description" => "Vị thanh ngọt của đào Hy Lạp, vị chua dịu của Cam Vàng nguyên vỏ, vị chát của trà đen tươi được ủ mới mỗi 4 tiếng, cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này.", "price" => "42000"],
        ["title" => "Trà Đào Cam Sả Nóng", "category_id" => 2, "link_image" => "/image/products/tea7.png", "description" => "Vị thanh ngọt của đào Hy Lạp, vị chua dịu của Cam Vàng nguyên vỏ, vị chát của trà đen tươi được ủ mới mỗi 4 tiếng, cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này.Uống đá sẽ cho một cảm giác mát mẻ, sảng khoái trong nhũng ngày hè.", "price" => "42000"],
        ["title" => "Trà Đào Cam Sả Đá", "category_id" => 2, "link_image" => "/image/products/tea8.png", "description" => "Nền trà ô long hảo hạng kết hợp cùng hạt sen tươi, bùi bùi và lớp foam cheese béo ngậy. Trà hạt sen là thức uống thanh mát, nhẹ nhàng phù hợp cho cả buổi sáng và chiều tối.", "price" => "35000", "favorite" => 1],
        ["title" => "Trà Long Nhãn Hạt Chia", "category_id" => 2, "link_image" => "/image/products/tea9.png", "description" => "Mát lạnh ngay từ ngụm đầu tiên, đọng lại cuối cùng là hương vị trà thơm lừng và vị ngọt thanh, chua dịu khó quên của trà long nhãn hạt chia.", "price" => "45000"],
        ["title" => "Trà Long Nhãn Hạt Chia Nóng", "category_id" => 2, "link_image" => "/image/products/tea10.png", "description" => "Vị nhãn ngọt, tươi mát đặc trưng hoà quyện tinh tế cùng vị trà oolong hảo hạng và hạt chia mang đến cho bạn một thức uống không chỉ thơm ngon mà còn bổ dưỡng.", "price" => "45000"],
        ["title" => "Bánh Mỳ Hoa Cúc", "category_id" => 3, "link_image" => "/image/products/1c.jpg", "description" => "Bánh xốp có mùi thơm lừng hương hoa cúc và vị mật ong dẻo mềm, với lớp đường rắc lên bánh không quá ngọt.", "price" => "20000"],
        ["title" => "Bánh Kem Mouse Red Velvet", "category_id" => 3, "link_image" => "/image/products/2c.jpg", "description" => "Bánh nhiều lớp được phủ lớp kem bên trên bằng Cream cheese.", "price" => "30000"],
        ["title" => "Bánh Kem Mouse Chanh Dây", "category_id" => 3, "link_image" => "/image/products/3c.jpg", "description" => "Tận hưởng chiếc bánh mát lạnh với sự kết hợp hoàn hảo của vị béo ngậy của nhân kem phô mai, cân bằng với vị chua thanh từ chanh dây.", "price" => "30000"],
        ["title" => "Tiramisu Kem Mouse", "category_id" => 3, "link_image" => "/image/products/4c.jpg", "description" => "Hương vị dễ ghiền được tạo nên bởi chút đắng nhẹ của cà phê, lớp kem trứng béo ngọt dịu hấp dẫn.", "price" => "35000"],
        ["title" => "Bánh Gấu Chocalate kem Mouso", "category_id" => 3, "link_image" => "/image/products/5c.jpg", "description" => "Với vẻ ngoài đáng yêu và hương vị ngọt ngào, thơm béo nhất định bạn phải thử ít nhất một lần.", "price" => "40000"],
        ["title" => "Bánh Phô Mai Cà phê", "category_id" => 3, "link_image" => "/image/products/6c.png", "description" => "Làm từ cà phê truyền thống của Highlands, kết hợp với phô mai thơm ngon! Chiếc bánh phù hợp đi cùng với bất cứ món cà phê nào!", "price" => "29000"],
        ["title" => "Bánh Phô Mai Trà Xanh", "category_id" => 3, "link_image" => "/image/products/7c.png", "description" => "Một sự sáng tạo mới mẻ, kết hợp giữa trà xanh đậm đà và phô mai ít béo.", "price" => "29000", "favorite" => 1],
        ["title" => "Bánh Caramel Phô Mai", "category_id" => 3, "link_image" => "/image/products/8c.png", "description" => "Ngon khó cưỡng! Bánh phô mai thơm béo được phủ bằng lớp caramel ngọt ngào.", "price" => "29000"],
        ["title" => "Tiramisu Mini", "category_id" => 3, "link_image" => "/image/products/9c.png", "description" => "Tiramisu thơm béo, làm từ ca-cao Việt Nam đậm đà, kết hợp với phô mai ít béo, vani và chút rum nhẹ nhàng.", "price" => "19000", "favorite" => 1],
        ["title" => "Bánh Chuối", "category_id" => 3, "link_image" => "/image/products/10c.png", "description" => "Bánh chuối truyền thống, sự kết hợp của 100% chuối tươi và nước cốt dừa Việt Nam.", "price" => "19000"],
        ["title" => "Bánh Mouse CaCao", "category_id" => 3, "link_image" => "/image/products/11c.png", "description" => "Bánh Mousse Ca Cao, là sự kết hợp giữa ca-cao Việt Nam đậm đà cùng kem tươi.", "price" => "29000", "favorite" => 1],
        ["title" => "Pure Butter Croissant", "category_id" => 3, "link_image" => "/image/products/12c.png", "description" => "Sẽ thật tuyệt khi khởi tạo năng lượng cùng cốc Cappuccino và món bánh Pure Butter Croissant thơm ngon làm từ 100% bơ nguyên chất", "price" => "20000"],
        ["title" => "Butter Chocolate Croissant", "category_id" => 3, "link_image" => "/image/products/13c.png", "description" => "Bánh sừng bò đặc biệt thơm bơ, là dòng bánh được khách hàng rất yêu thích.", "price" => "22000"],
        ["title" => "Raisin Danish", "category_id" => 3, "link_image" => "/image/products/14c.png", "description" => "Nho khô trộn lẫn với lớp kem trứng thanh mịn, được cuộn lại bằng những dải bột ngàn lớp giòn tan là sự kết hợp hoàn hảo cho món bánh cuộn nho siêu đặc biệt này.", "price" => "22000", "favorite" => 1],
        ["title" => "Green Tea Choco Cake", "category_id" => 3, "link_image" => "/image/products/15c.png", "description" => "Greentea and Chocolate cake với sự kết hợp giữa vị đắng của trà xanh và sự ngọt ngào của Chocolate thêm vị béo thơm của bơ tạo nên món bánh ngon tuyệt.", "price" => "35000"],
        ["title" => "Passion Panna Cotta", "category_id" => 3, "link_image" => "/image/products/16c.png", "description" => "Panna Cotta chanh dây mềm mịn, có vị béo và ngọt vừa phải của whipping cream cùng mùi thơm của chanh dây vô cùng hấp dẫn, mới nghe thôi là đã muốn thưởng thức.", "price" => "35000"],
        ["title" => "Tiramisu Dâu Chocolate", "category_id" => 3, "link_image" => "/image/products/17c.png", "description" => "Bánh mềm xốp với kem mascarpone trắng mịn, thơm ngậy ngọt ngào.", "price" => "35000", "favorite" => 1],
        ["title" => "Bánh Chocolate Dâu", "category_id" => 3, "link_image" => "/image/products/18c.png", "description" => "Một chiếc bánh độc đáo! Sô cô la ngọt ngào và kem tươi béo ngậy, được phủ thêm một lớp sô cô la mỏng bên trên cho thêm phần hấp dẫn.", "price" => "29000"]
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach($this->products as $key => $product){
            $product['product_code'] = str_pad($key + 1, 8, "0", STR_PAD_LEFT);
            Product::create($product);
        }
    }
}
